apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-service
spec:
  rules:
  - host: simple-app  # Change to your desired hostname
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: api-nodeport-service
            port:
              number: 8089

